// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {sql} from '../models';

export function DeleteClientByID(arg1:number):Promise<void>;

export function GetAllClient():Promise<Array<client.Client>>;

export function GetClientByID(arg1:number):Promise<client.Client>;

export function InitTable(arg1:sql.DB):Promise<void>;

export function InsertClient(arg1:client.Client):Promise<void>;
