// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sql} from '../models';
import {client} from '../models';

export function InitTable(arg1:sql.DB):Promise<void>;

export function InsertClient(arg1:client.Client):Promise<void>;
