// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllClient() {
  return window['go']['client']['ClientMananger']['GetAllClient']();
}

export function InitTable(arg1) {
  return window['go']['client']['ClientMananger']['InitTable'](arg1);
}

export function InsertClient(arg1) {
  return window['go']['client']['ClientMananger']['InsertClient'](arg1);
}
